/**
 * Anchor integration tests for programs/flacon (briefing §6, tests a–g).
 * Runs against the local validator started by `anchor test`.
 *
 * Fixtures: docs/vectors.json and docs/enums.json (generated by packages/proof — never edited here).
 */
import * as anchor from "@anchor-lang/core";
import { BN, Program } from "@anchor-lang/core";
import {
  Ed25519Program,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SYSVAR_INSTRUCTIONS_PUBKEY,
  SystemProgram,
  TransactionInstruction,
} from "@solana/web3.js";
import { expect } from "chai";
import * as fs from "fs";
import * as path from "path";
import nacl from "tweetnacl";
import type { Flacon } from "../target/types/flacon";

// ---------------------------------------------------------------------------
// fixtures
// ---------------------------------------------------------------------------

const ROOT = path.join(__dirname, "..");
const vectors = JSON.parse(fs.readFileSync(path.join(ROOT, "docs/vectors.json"), "utf8"));
const enums = JSON.parse(fs.readFileSync(path.join(ROOT, "docs/enums.json"), "utf8"));

const SEEDS = vectors.constants.PDA_SEEDS as Record<string, string>;
const MSG_PREFIX: string = vectors.constants.MSG_PREFIX;
const MSG_LEN: number = vectors.constants.MSG_LEN;

const serverKp = nacl.sign.keyPair.fromSeed(Buffer.from(vectors.serverTestKey.seedHex, "hex"));
const serverPubkey = Buffer.from(vectors.serverTestKey.pubkeyHex, "hex");
const SERVER_KEY_ID: number = vectors.serverTestKey.keyId;

const hex = (h: string) => Buffer.from(h, "hex");
const bytes = (b: Buffer | Uint8Array) => Array.from(b);
const label32 = (s: string): number[] => {
  const b = Buffer.alloc(32);
  Buffer.from(s, "utf8").copy(b);
  return bytes(b);
};

type ScanInput = {
  serial: string;
  uidHex: string;
  counter: number;
  tier: number;
  role: number;
  tamper: number;
  uv: number;
  hum: number;
  heat: number;
  heatLevels: number[];
  fill: number;
  mediaHashHex: string;
  nonceHex: string;
  ts: number;
};
type ScanVector = {
  name: string;
  input: ScanInput;
  serialHashHex: string;
  uidHashHex: string;
  heatMask: number;
  msgHex: string;
  sigHex: string;
  grade: number;
  bundleHashHex: string;
};
const scans: ScanVector[] = vectors.scans;
const scan0 = scans[0];

// ---------------------------------------------------------------------------
// §4.3 message + §4.5 grade — the same rule as packages/proof, re-implemented
// here so the test does not depend on the ESM build of packages/proof.
// ---------------------------------------------------------------------------

interface MsgFields {
  serialHash: Buffer;
  uidHash: Buffer;
  counter: number;
  tamper: number;
  uv: number;
  hum: number;
  heat: number;
  fill: number;
  mediaHash: Buffer;
  nonce: Buffer;
  ts: number | bigint;
}
function buildScanMessage(f: MsgFields): Buffer {
  const m = Buffer.alloc(MSG_LEN);
  m.write(MSG_PREFIX, 0, "ascii");
  f.serialHash.copy(m, 7);
  f.uidHash.copy(m, 39);
  m.writeUInt32LE(f.counter, 71);
  m[75] = f.tamper;
  m[76] = f.uv;
  m[77] = f.hum;
  m[78] = f.heat;
  m[79] = f.fill;
  f.mediaHash.copy(m, 80);
  f.nonce.copy(m, 112);
  m.writeBigInt64LE(BigInt(f.ts), 144);
  return m;
}
const heatMask = (levels: number[]) => levels.reduce((m, v, i) => (v ? m | (1 << i) : m), 0);

const G = enums.grade as Record<string, number>;
const I = enums.indicator as Record<string, number>;
const T = enums.tamper as Record<string, number>;
const FILL_A_MIN = 90;
const FILL_B_MIN = 60;
function gradeRule(i: {
  verdict?: string;
  sealDead?: boolean;
  tamper: number;
  heat: number;
  hum: number;
  fill: number;
}): number {
  if ((i.verdict ?? "VALID") !== "VALID" || i.sealDead) return G.VOID;
  if (i.tamper === T.OPENED_NOW || i.tamper === T.OPENED_BEFORE) return G.VOID;
  if (i.heat === I.TRIGGERED || i.hum === I.TRIGGERED) return G.C;
  if (i.fill >= FILL_A_MIN) return G.A;
  if (i.fill >= FILL_B_MIN) return G.B;
  return G.D;
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function signMessage(msg: Buffer): Buffer {
  return Buffer.from(nacl.sign.detached(msg, serverKp.secretKey));
}
function ed25519Ix(msg: Buffer, sig: Buffer, publicKey: Buffer = serverPubkey): TransactionInstruction {
  return Ed25519Program.createInstructionWithPublicKey({ publicKey, message: msg, signature: sig });
}

/** Asserts that the promise rejects with the given Anchor error code. */
async function expectAnchorError(p: Promise<unknown>, code: string, idlErrors: { code: number; name: string }[]) {
  try {
    await p;
  } catch (e: any) {
    let got: string | undefined = e?.error?.errorCode?.code;
    if (!got) {
      const logs: string[] = e?.logs ?? e?.transactionLogs ?? [];
      const m = logs.map((l) => /Error Code: (\w+)/.exec(l)).find(Boolean);
      if (m) got = m[1];
    }
    if (!got) {
      const m = /custom program error: (0x[0-9a-fA-F]+)/.exec(String(e?.message ?? e));
      if (m) got = idlErrors.find((x) => x.code === parseInt(m[1], 16))?.name;
    }
    expect(got, `expected error ${code}, got: ${e?.message ?? e}`).to.equal(code);
    return;
  }
  expect.fail(`expected transaction to fail with ${code}`);
}

// ---------------------------------------------------------------------------

describe("flacon", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = anchor.workspace.flacon as Program<Flacon>;
  const wallet = provider.wallet.publicKey;
  const idlErrors = (program.idl.errors ?? []) as { code: number; name: string }[];

  const [registryPda] = PublicKey.findProgramAddressSync([Buffer.from(SEEDS.registry)], program.programId);
  const serialHash = hex(scan0.serialHashHex);
  const uidHash = hex(scan0.uidHashHex);
  const bindingHash = hex(vectors.hashes.binding[0].sha256Hex);
  const [passportPda] = PublicKey.findProgramAddressSync([Buffer.from(SEEDS.passport), serialHash], program.programId);
  const [sealPda] = PublicKey.findProgramAddressSync([Buffer.from(SEEDS.seal), uidHash], program.programId);
  const scanPda = (counter: number) => {
    const c = Buffer.alloc(4);
    c.writeUInt32LE(counter);
    return PublicKey.findProgramAddressSync([Buffer.from(SEEDS.scan), sealPda.toBuffer(), c], program.programId)[0];
  };
  const asset = Keypair.generate().publicKey;

  const SITE_1 = { id: 1, label: "Parfümerie X, Düsseldorf" };
  const SITE_2 = { id: 2, label: "FlaconVault Vault, Wickede" };

  /** record_scan args from a vector input (heat_levels as 6-bit mask). */
  function argsFrom(v: ScanVector, overrides: Partial<Record<string, any>> = {}) {
    const i = v.input;
    return {
      counter: i.counter,
      tier: i.tier,
      role: i.role,
      tamper: i.tamper,
      uv: i.uv,
      hum: i.hum,
      heat: i.heat,
      heatLevels: heatMask(i.heatLevels),
      fill: i.fill,
      siteId: 0,
      mediaHash: bytes(hex(i.mediaHashHex)),
      bundleHash: bytes(hex(v.bundleHashHex)),
      nonce: bytes(hex(i.nonceHex)),
      ts: new BN(i.ts),
      serverKeyId: SERVER_KEY_ID,
      ...overrides,
    };
  }
  /** Message for a given args object, bound to the test passport/seal. */
  function msgFor(a: ReturnType<typeof argsFrom>): Buffer {
    return buildScanMessage({
      serialHash,
      uidHash,
      counter: a.counter,
      tamper: a.tamper,
      uv: a.uv,
      hum: a.hum,
      heat: a.heat,
      fill: a.fill,
      mediaHash: Buffer.from(a.mediaHash),
      nonce: Buffer.from(a.nonce),
      ts: BigInt(a.ts.toString()),
    });
  }
  function recordScanBuilder(a: ReturnType<typeof argsFrom>, attester: PublicKey = wallet) {
    return program.methods.recordScan(a).accountsStrict({
      registry: registryPda,
      passport: passportPda,
      seal: sealPda,
      scanProof: scanPda(a.counter),
      attester,
      instructions: SYSVAR_INSTRUCTIONS_PUBKEY,
      systemProgram: SystemProgram.programId,
    });
  }

  // -------------------------------------------------------------------------

  it("TS message builder reproduces vectors.scans[*].msgHex and the signatures verify", () => {
    for (const s of scans) {
      const i = s.input;
      const m = buildScanMessage({
        serialHash: hex(s.serialHashHex),
        uidHash: hex(s.uidHashHex),
        counter: i.counter,
        tamper: i.tamper,
        uv: i.uv,
        hum: i.hum,
        heat: i.heat,
        fill: i.fill,
        mediaHash: hex(i.mediaHashHex),
        nonce: hex(i.nonceHex),
        ts: i.ts,
      });
      expect(m.toString("hex"), s.name).to.equal(s.msgHex);
      expect(nacl.sign.detached.verify(m, hex(s.sigHex), serverPubkey), `${s.name} sig`).to.be.true;
      expect(heatMask(i.heatLevels), `${s.name} heatMask`).to.equal(s.heatMask);
    }
    expect(Buffer.from(serverKp.publicKey).toString("hex")).to.equal(vectors.serverTestKey.pubkeyHex);
  });

  it("(a) init registry, server key, partner, 2 sites", async () => {
    await program.methods
      .initRegistry()
      .accountsStrict({ registry: registryPda, authority: wallet, systemProgram: SystemProgram.programId })
      .rpc();
    await program.methods
      .addServerKey(SERVER_KEY_ID, bytes(serverPubkey), new BN(0), new BN(0))
      .accountsStrict({ registry: registryPda, authority: wallet })
      .rpc();
    await program.methods.addPartner(wallet).accountsStrict({ registry: registryPda, authority: wallet }).rpc();
    await program.methods
      .addSite(SITE_1.id, label32(SITE_1.label))
      .accountsStrict({ registry: registryPda, authority: wallet })
      .rpc();
    await program.methods
      .addSite(SITE_2.id, label32(SITE_2.label))
      .accountsStrict({ registry: registryPda, authority: wallet })
      .rpc();

    const reg = await program.account.registry.fetch(registryPda);
    expect(reg.authority.equals(wallet)).to.be.true;
    expect(reg.serverKeys).to.have.length(1);
    expect(reg.serverKeys[0].keyId).to.equal(SERVER_KEY_ID);
    expect(Buffer.from(reg.serverKeys[0].pubkey).toString("hex")).to.equal(vectors.serverTestKey.pubkeyHex);
    expect(reg.serverKeys[0].validFrom.toNumber()).to.equal(0);
    expect(reg.serverKeys[0].validTo.toNumber()).to.equal(0);
    expect(reg.partners.map((p) => p.toBase58())).to.deep.equal([wallet.toBase58()]);
    expect(reg.sites.map((s) => s.siteId)).to.deep.equal([1, 2]);
    expect(Buffer.from(reg.sites[0].label).toString("utf8").replace(/\0+$/, "")).to.equal(SITE_1.label);
    expect(Buffer.from(reg.sites[1].label).toString("utf8").replace(/\0+$/, "")).to.equal(SITE_2.label);
  });

  it("registry admin rejects duplicates and non-authority", async () => {
    await expectAnchorError(
      program.methods
        .addServerKey(SERVER_KEY_ID, bytes(serverPubkey), new BN(0), new BN(0))
        .accountsStrict({ registry: registryPda, authority: wallet })
        .rpc(),
      "DuplicateServerKey",
      idlErrors
    );
    await expectAnchorError(
      program.methods.addPartner(wallet).accountsStrict({ registry: registryPda, authority: wallet }).rpc(),
      "DuplicatePartner",
      idlErrors
    );
    await expectAnchorError(
      program.methods
        .addSite(SITE_1.id, label32("dup"))
        .accountsStrict({ registry: registryPda, authority: wallet })
        .rpc(),
      "DuplicateSite",
      idlErrors
    );
    const stranger = Keypair.generate();
    await expectAnchorError(
      program.methods
        .addPartner(stranger.publicKey)
        .accountsStrict({ registry: registryPda, authority: stranger.publicKey })
        .signers([stranger])
        .rpc(),
      "Unauthorized",
      idlErrors
    );
  });

  it("(a) mint passport + attach NECK seal", async () => {
    await program.methods
      .mintPassport(bytes(serialHash), bytes(bindingHash), asset)
      .accountsStrict({
        registry: registryPda,
        passport: passportPda,
        issuer: wallet,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    const p = await program.account.passport.fetch(passportPda);
    expect(Buffer.from(p.serialHash).toString("hex")).to.equal(scan0.serialHashHex);
    expect(Buffer.from(p.bindingHash).toString("hex")).to.equal(vectors.hashes.binding[0].sha256Hex);
    expect(p.asset.equals(asset)).to.be.true;
    expect(p.issuer.equals(wallet)).to.be.true;
    expect(p.grade).to.equal(G.A);
    expect(p.scanCount).to.equal(0);
    expect(p.sealCount).to.equal(0);
    expect(p.void).to.be.false;
    expect(p.createdAt.toNumber()).to.be.greaterThan(0);

    // kind 2 (LOOP) is reserved
    await expectAnchorError(
      program.methods
        .attachSeal(bytes(uidHash), 2)
        .accountsStrict({
          registry: registryPda,
          passport: passportPda,
          seal: sealPda,
          signer: wallet,
          systemProgram: SystemProgram.programId,
        })
        .rpc(),
      "InvalidSealKind",
      idlErrors
    );

    await program.methods
      .attachSeal(bytes(uidHash), enums.seal_kind.NECK)
      .accountsStrict({
        registry: registryPda,
        passport: passportPda,
        seal: sealPda,
        signer: wallet,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    const s = await program.account.seal.fetch(sealPda);
    expect(s.passport.equals(passportPda)).to.be.true;
    expect(s.kind).to.equal(enums.seal_kind.NECK);
    expect(Buffer.from(s.uidHash).toString("hex")).to.equal(scan0.uidHashHex);
    expect(s.lastCounter).to.equal(0);
    expect(s.dead).to.be.false;
    expect((await program.account.passport.fetch(passportPda)).sealCount).to.equal(1);
  });

  it("mint/attach by a non-partner fails with NotPartner", async () => {
    const stranger = Keypair.generate();
    const sig = await provider.connection.requestAirdrop(stranger.publicKey, LAMPORTS_PER_SOL);
    await provider.connection.confirmTransaction(sig, "confirmed");
    const otherSerial = hex(vectors.hashes.serial[1].sha256Hex);
    const [otherPassport] = PublicKey.findProgramAddressSync(
      [Buffer.from(SEEDS.passport), otherSerial],
      program.programId
    );
    await expectAnchorError(
      program.methods
        .mintPassport(bytes(otherSerial), bytes(bindingHash), asset)
        .accountsStrict({
          registry: registryPda,
          passport: otherPassport,
          issuer: stranger.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([stranger])
        .rpc(),
      "NotPartner",
      idlErrors
    );
  });

  it("(b) record_scan without the ed25519 instruction fails", async () => {
    // scans[0] (counter 14) is still unused at this point — only the ed25519 check can fail
    const a = argsFrom(scan0);
    await expectAnchorError(recordScanBuilder(a).rpc(), "MissingEd25519Instruction", idlErrors);
  });

  it("(b') ed25519 instruction signed by a different key fails", async () => {
    const a = argsFrom(scans[1]);
    const msg = msgFor(a);
    const other = nacl.sign.keyPair();
    const sig = Buffer.from(nacl.sign.detached(msg, other.secretKey));
    await expectAnchorError(
      recordScanBuilder(a)
        .preInstructions([ed25519Ix(msg, sig, Buffer.from(other.publicKey))])
        .rpc(),
      "ServerKeyMismatch",
      idlErrors
    );
    await expectAnchorError(
      recordScanBuilder({ ...a, serverKeyId: 9 })
        .preInstructions([ed25519Ix(msg, signMessage(msg))])
        .rpc(),
      "UnknownServerKey",
      idlErrors
    );
  });

  it("(c) same as (a) but fill + 1: message no longer matches", async () => {
    // still before (a): counter 14 unused, so the failure is purely the message check
    const a = argsFrom(scan0, { fill: scan0.input.fill + 1 });
    await expectAnchorError(
      recordScanBuilder(a)
        .preInstructions([ed25519Ix(hex(scan0.msgHex), hex(scan0.sigHex))])
        .rpc(),
      "MessageMismatch",
      idlErrors
    );
  });

  it("(a) record_scan for scans[0] with the vector signature", async () => {
    const a = argsFrom(scan0);
    const msg = msgFor(a);
    expect(msg.toString("hex")).to.equal(scan0.msgHex);

    await recordScanBuilder(a)
      .preInstructions([ed25519Ix(msg, hex(scan0.sigHex))])
      .rpc();

    const sp = await program.account.scanProof.fetch(scanPda(scan0.input.counter));
    expect(sp.seal.equals(sealPda)).to.be.true;
    expect(sp.counter).to.equal(14);
    expect(sp.tier).to.equal(scan0.input.tier);
    expect(sp.role).to.equal(scan0.input.role);
    expect(sp.tamper).to.equal(scan0.input.tamper);
    expect(sp.uv).to.equal(scan0.input.uv);
    expect(sp.hum).to.equal(scan0.input.hum);
    expect(sp.heat).to.equal(scan0.input.heat);
    expect(sp.heatLevels).to.equal(scan0.heatMask);
    expect(sp.fill).to.equal(scan0.input.fill);
    expect(sp.siteId).to.equal(0);
    expect(Buffer.from(sp.mediaHash).toString("hex")).to.equal(scan0.input.mediaHashHex);
    expect(Buffer.from(sp.bundleHash).toString("hex")).to.equal(scan0.bundleHashHex);
    expect(sp.attester.equals(wallet)).to.be.true;
    expect(sp.serverKeyId).to.equal(SERVER_KEY_ID);
    expect(sp.ts.toNumber()).to.equal(scan0.input.ts);

    const seal = await program.account.seal.fetch(sealPda);
    expect(seal.lastCounter).to.equal(14);
    const p = await program.account.passport.fetch(passportPda);
    expect(p.grade).to.equal(scan0.grade);
    expect(p.scanCount).to.equal(1);
  });

  it("(d) counter 14 again / counter 13 fail with CounterNotIncreasing", async () => {
    const same = argsFrom(scan0);
    await expectAnchorError(
      recordScanBuilder(same)
        .preInstructions([ed25519Ix(hex(scan0.msgHex), hex(scan0.sigHex))])
        .rpc(),
      "CounterNotIncreasing",
      idlErrors
    );
    const older = argsFrom(scan0, { counter: 13 });
    const msg = msgFor(older);
    await expectAnchorError(
      recordScanBuilder(older).preInstructions([ed25519Ix(msg, signMessage(msg))]).rpc(),
      "CounterNotIncreasing",
      idlErrors
    );
  });

  it("(e) tier 3 with a non-partner attester fails with NotPartner", async () => {
    const outsider = Keypair.generate();
    const sig = await provider.connection.requestAirdrop(outsider.publicKey, LAMPORTS_PER_SOL);
    await provider.connection.confirmTransaction(sig, "confirmed");

    const a = argsFrom(scan0, { counter: 16, tier: enums.tier.CERTIFIED, role: enums.role.VAULT });
    const msg = msgFor(a);
    await expectAnchorError(
      recordScanBuilder(a, outsider.publicKey)
        .preInstructions([ed25519Ix(msg, signMessage(msg))])
        .signers([outsider])
        .rpc(),
      "NotPartner",
      idlErrors
    );

    // SELLER may not attest tier 3 at all
    const b = argsFrom(scan0, { counter: 16, tier: enums.tier.CERTIFIED, role: enums.role.SELLER });
    const msgB = msgFor(b);
    await expectAnchorError(
      recordScanBuilder(b).preInstructions([ed25519Ix(msgB, signMessage(msgB))]).rpc(),
      "TierNotAllowedForRole",
      idlErrors
    );

    // site_id only for VAULT/PARTNER
    const c = argsFrom(scan0, { counter: 16, siteId: 1 });
    const msgC = msgFor(c);
    await expectAnchorError(
      recordScanBuilder(c).preInstructions([ed25519Ix(msgC, signMessage(msgC))]).rpc(),
      "SiteIdNotAllowed",
      idlErrors
    );

    // heat must agree with bit 4 of heat_levels
    const d = argsFrom(scan0, { counter: 16, heat: I.TRIGGERED });
    const msgD = msgFor(d);
    await expectAnchorError(
      recordScanBuilder(d).preInstructions([ed25519Ix(msgD, signMessage(msgD))]).rpc(),
      "HeatInconsistent",
      idlErrors
    );
  });

  it("partner tier-3 VAULT scan with site_id and triggered heat → grade C", async () => {
    // scans[1]: heat triggered, counter 15 — as a certified vault scan at site 2
    const a = argsFrom(scans[1], { tier: enums.tier.CERTIFIED, role: enums.role.VAULT, siteId: SITE_2.id });
    const msg = msgFor(a);
    await recordScanBuilder(a).preInstructions([ed25519Ix(msg, signMessage(msg))]).rpc();

    const sp = await program.account.scanProof.fetch(scanPda(15));
    expect(sp.siteId).to.equal(SITE_2.id);
    expect(sp.tier).to.equal(enums.tier.CERTIFIED);
    expect(sp.heat).to.equal(I.TRIGGERED);
    expect(sp.heatLevels).to.equal(scans[1].heatMask);
    const p = await program.account.passport.fetch(passportPda);
    expect(p.grade).to.equal(G.C);
    expect(p.grade).to.equal(scans[1].grade);
    expect(p.scanCount).to.equal(2);
    expect((await program.account.seal.fetch(sealPda)).lastCounter).to.equal(15);
  });

  it("(f) mark_seal_dead → further scan fails with SealDead, passport VOID", async () => {
    await program.methods
      .markSealDead()
      .accountsStrict({ registry: registryPda, passport: passportPda, seal: sealPda, signer: wallet })
      .rpc();

    const seal = await program.account.seal.fetch(sealPda);
    expect(seal.dead).to.be.true;
    const p = await program.account.passport.fetch(passportPda);
    expect(p.void).to.be.true;
    expect(p.grade).to.equal(G.VOID);
    expect(p.grade).to.equal(4);

    const a = argsFrom(scan0, { counter: 20 });
    const msg = msgFor(a);
    await expectAnchorError(
      recordScanBuilder(a).preInstructions([ed25519Ix(msg, signMessage(msg))]).rpc(),
      "SealDead",
      idlErrors
    );
    expect((await program.account.passport.fetch(passportPda)).scanCount).to.equal(2);
  });

  it("(g) IDL constants equal docs/enums.json and vectors.constants", () => {
    // the client camel-cases IDL names; the raw IDL (as built) keeps SCREAMING_SNAKE
    const rawIdl = (program as any).rawIdl ?? JSON.parse(fs.readFileSync(path.join(ROOT, "target/idl/flacon.json"), "utf8"));
    const consts = (rawIdl.constants ?? []) as { name: string; type: any; value: string }[];
    expect(consts.length).to.be.greaterThan(40);
    const byName = new Map(consts.map((c) => [c.name, c]));
    const constValue = (name: string) => {
      const c = byName.get(name);
      expect(c, `IDL constant ${name}`).to.not.be.undefined;
      return c!.value;
    };
    const constBytes = (name: string): Buffer => {
      const v = constValue(name);
      // byte constants are rendered as `b"..."` or as a JSON array of numbers
      const m = /^b"(.*)"$/.exec(v);
      if (m) return Buffer.from(m[1], "ascii");
      const j = JSON.parse(v);
      if (Array.isArray(j)) return Buffer.from(j);
      return Buffer.from(String(j), "ascii");
    };

    // enums
    for (const [group, values] of Object.entries(enums) as [string, any][]) {
      if (typeof values !== "object" || Array.isArray(values)) continue;
      for (const [key, val] of Object.entries(values as Record<string, number>)) {
        const name = `${group.toUpperCase()}_${key}`;
        expect(constValue(name), name).to.equal(String(val));
      }
    }
    // message + seeds
    expect(constBytes("MSG_PREFIX").toString("ascii")).to.equal(MSG_PREFIX);
    expect(constValue("MSG_LEN")).to.equal(String(MSG_LEN));
    for (const [k, seed] of Object.entries(SEEDS)) {
      expect(constBytes(`${k.toUpperCase()}_SEED`).toString("ascii"), k).to.equal(seed);
    }
    expect(constValue("HEAT_DECISIVE_INDEX")).to.equal(String(vectors.constants.HEAT_DECISIVE_INDEX));
    // grade rule thresholds
    expect(constValue("GRADE_FILL_A_MIN")).to.equal(String(FILL_A_MIN));
    expect(constValue("GRADE_FILL_B_MIN")).to.equal(String(FILL_B_MIN));
    expect(constValue("MAX_SERVER_KEYS")).to.equal("8");
    expect(constValue("MAX_PARTNERS")).to.equal("16");
    expect(constValue("MAX_SITES")).to.equal("16");
  });

  it("(g) grade rule in TS matches vectors.grades (18 rows) and vectors.scans", () => {
    const rows = vectors.grades as any[];
    expect(rows).to.have.length(18);
    for (const r of rows) {
      expect(gradeRule(r), JSON.stringify(r)).to.equal(r.grade);
    }
    for (const s of scans) {
      if (s.input.tamper !== T.UNKNOWN) continue;
      expect(gradeRule(s.input), s.name).to.equal(s.grade);
    }
  });
});
