/**
 * Shared test helpers for programs/flacon (used by tests/flacon.ts and tests/escrow.ts).
 * Fixtures: docs/vectors.json, docs/enums.json (generated by packages/proof — never edited here).
 */
import * as anchor from "@anchor-lang/core";
import { BN, Program } from "@anchor-lang/core";
import {
  Ed25519Program,
  Keypair,
  PublicKey,
  SYSVAR_INSTRUCTIONS_PUBKEY,
  SystemProgram,
  TransactionInstruction,
} from "@solana/web3.js";
import { expect } from "chai";
import { createHash, randomBytes } from "crypto";
import * as fs from "fs";
import * as path from "path";
import nacl from "tweetnacl";

export const ROOT = path.join(__dirname, "../..");
export const vectors = JSON.parse(fs.readFileSync(path.join(ROOT, "docs/vectors.json"), "utf8"));
export const enums = JSON.parse(fs.readFileSync(path.join(ROOT, "docs/enums.json"), "utf8"));

export const SEEDS = vectors.constants.PDA_SEEDS as Record<string, string>;
export const MSG_PREFIX: string = vectors.constants.MSG_PREFIX;
export const MSG_LEN: number = vectors.constants.MSG_LEN;

/** TEST ONLY server key (docs/vectors.json serverTestKey). */
export const serverKp = nacl.sign.keyPair.fromSeed(Buffer.from(vectors.serverTestKey.seedHex, "hex"));
export const serverPubkey = Buffer.from(vectors.serverTestKey.pubkeyHex, "hex");
export const SERVER_KEY_ID_DEFAULT: number = vectors.serverTestKey.keyId;

export const hex = (h: string) => Buffer.from(h, "hex");
export const bytes = (b: Buffer | Uint8Array) => Array.from(b);
export const sha256 = (b: Buffer | string) => createHash("sha256").update(b).digest();
export const label32 = (s: string): number[] => {
  const b = Buffer.alloc(32);
  Buffer.from(s, "utf8").copy(b);
  return bytes(b);
};

export const SITE_1 = { id: 1, label: "Parfümerie X, Düsseldorf" };
export const SITE_2 = { id: 2, label: "FlaconVault Vault, Wickede" };

// ---------------------------------------------------------------------------
// §4.3 message — the same layout as packages/proof, re-implemented here so the
// tests do not depend on the ESM build of packages/proof.
// ---------------------------------------------------------------------------

export interface MsgFields {
  serialHash: Buffer;
  uidHash: Buffer;
  counter: number;
  tamper: number;
  uv: number;
  hum: number;
  heat: number;
  fill: number;
  mediaHash: Buffer;
  nonce: Buffer;
  ts: number | bigint;
}
export function buildScanMessage(f: MsgFields): Buffer {
  const m = Buffer.alloc(MSG_LEN);
  m.write(MSG_PREFIX, 0, "ascii");
  f.serialHash.copy(m, 7);
  f.uidHash.copy(m, 39);
  m.writeUInt32LE(f.counter, 71);
  m[75] = f.tamper;
  m[76] = f.uv;
  m[77] = f.hum;
  m[78] = f.heat;
  m[79] = f.fill;
  f.mediaHash.copy(m, 80);
  f.nonce.copy(m, 112);
  m.writeBigInt64LE(BigInt(f.ts), 144);
  return m;
}
export const heatMask = (levels: number[]) => levels.reduce((m, v, i) => (v ? m | (1 << i) : m), 0);

export function signMessage(msg: Buffer): Buffer {
  return Buffer.from(nacl.sign.detached(msg, serverKp.secretKey));
}
export function ed25519Ix(msg: Buffer, sig: Buffer, publicKey: Buffer = serverPubkey): TransactionInstruction {
  return Ed25519Program.createInstructionWithPublicKey({ publicKey, message: msg, signature: sig });
}

/** Asserts that the promise rejects with the given Anchor error code. */
export async function expectAnchorError(
  p: Promise<unknown>,
  code: string,
  idlErrors: { code: number; name: string }[] = []
) {
  try {
    await p;
  } catch (e: any) {
    let got: string | undefined = e?.error?.errorCode?.code;
    if (!got) {
      const logs: string[] = e?.logs ?? e?.transactionLogs ?? [];
      const m = logs.map((l) => /Error Code: (\w+)/.exec(l)).find(Boolean);
      if (m) got = m[1];
    }
    if (!got) {
      const m = /custom program error: (0x[0-9a-fA-F]+)/.exec(String(e?.message ?? e));
      if (m) got = idlErrors.find((x) => x.code === parseInt(m[1], 16))?.name;
    }
    expect(got, `expected error ${code}, got: ${e?.message ?? e}`).to.equal(code);
    return;
  }
  expect.fail(`expected transaction to fail with ${code}`);
}

// ---------------------------------------------------------------------------
// PDAs
// ---------------------------------------------------------------------------

export const registryPdaOf = (programId: PublicKey) =>
  PublicKey.findProgramAddressSync([Buffer.from(SEEDS.registry)], programId)[0];
export const passportPdaOf = (programId: PublicKey, serialHash: Buffer) =>
  PublicKey.findProgramAddressSync([Buffer.from(SEEDS.passport), serialHash], programId)[0];
export const sealPdaOf = (programId: PublicKey, uidHash: Buffer) =>
  PublicKey.findProgramAddressSync([Buffer.from(SEEDS.seal), uidHash], programId)[0];
export const scanPdaOf = (programId: PublicKey, seal: PublicKey, counter: number) => {
  const c = Buffer.alloc(4);
  c.writeUInt32LE(counter);
  return PublicKey.findProgramAddressSync([Buffer.from(SEEDS.scan), seal.toBuffer(), c], programId)[0];
};

// ---------------------------------------------------------------------------
// Idempotent registry setup: registry + test server key + partner(wallet) + sites 1/2.
// Works on a fresh validator and on one seeded by scripts/seed-devnet.ts (where key_id 1
// may hold a different server key — the test key is then added under the next free id).
// ---------------------------------------------------------------------------

export interface RegistryHandle {
  registryPda: PublicKey;
  /** key_id under which the vectors test server key is registered */
  serverKeyId: number;
  created: boolean;
}

export async function ensureRegistry(program: Program<any>, wallet: PublicKey): Promise<RegistryHandle> {
  const registryPda = registryPdaOf(program.programId);
  const admin = { registry: registryPda, authority: wallet };
  const registryAccount = (program.account as any).registry;
  let reg = await registryAccount.fetchNullable(registryPda);
  let created = false;
  if (!reg) {
    await program.methods
      .initRegistry()
      .accountsStrict({ ...admin, systemProgram: SystemProgram.programId })
      .rpc();
    created = true;
    reg = await registryAccount.fetch(registryPda);
  }
  let key = reg.serverKeys.find((k: any) => Buffer.from(k.pubkey).equals(serverPubkey));
  if (!key) {
    const used = new Set<number>(reg.serverKeys.map((k: any) => k.keyId));
    let id = SERVER_KEY_ID_DEFAULT;
    while (used.has(id)) id++;
    await program.methods.addServerKey(id, bytes(serverPubkey), new BN(0), new BN(0)).accountsStrict(admin).rpc();
    key = { keyId: id };
  }
  if (!reg.partners.some((p: PublicKey) => p.equals(wallet))) {
    await program.methods.addPartner(wallet).accountsStrict(admin).rpc();
  }
  for (const s of [SITE_1, SITE_2]) {
    if (!reg.sites.some((x: any) => x.siteId === s.id)) {
      await program.methods.addSite(s.id, label32(s.label)).accountsStrict(admin).rpc();
    }
  }
  return { registryPda, serverKeyId: key.keyId, created };
}

// ---------------------------------------------------------------------------
// Passport + seal + scan helpers
// ---------------------------------------------------------------------------

export interface PassportHandle {
  serial: string;
  serialHash: Buffer;
  uidHash: Buffer;
  passportPda: PublicKey;
  sealPda: PublicKey;
  asset: PublicKey;
}

/** Mints a passport (issuer = wallet, must be partner) and attaches one seal. */
export async function mintPassportWithSeal(
  program: Program<any>,
  registryPda: PublicKey,
  wallet: PublicKey,
  opts: { serial?: string; uid?: Buffer; asset?: PublicKey; kind?: number; bindingHash?: Buffer } = {}
): Promise<PassportHandle> {
  const serial = opts.serial ?? `SN-TEST-${randomBytes(6).toString("hex")}`;
  const serialHash = sha256(serial);
  const uid = opts.uid ?? randomBytes(7);
  const uidHash = sha256(uid);
  const asset = opts.asset ?? Keypair.generate().publicKey;
  const bindingHash = opts.bindingHash ?? sha256(Buffer.concat([Buffer.from(serial), Buffer.from("TEST"), uidHash]));
  const passportPda = passportPdaOf(program.programId, serialHash);
  const sealPda = sealPdaOf(program.programId, uidHash);
  await program.methods
    .mintPassport(bytes(serialHash), bytes(bindingHash), asset)
    .accountsStrict({ registry: registryPda, passport: passportPda, issuer: wallet, systemProgram: SystemProgram.programId })
    .rpc();
  await program.methods
    .attachSeal(bytes(uidHash), opts.kind ?? enums.seal_kind.NECK)
    .accountsStrict({ registry: registryPda, passport: passportPda, seal: sealPda, signer: wallet, systemProgram: SystemProgram.programId })
    .rpc();
  return { serial, serialHash, uidHash, passportPda, sealPda, asset };
}

export interface ScanOpts {
  counter: number;
  fill: number;
  role?: number;
  tier?: number;
  heat?: number;
  hum?: number;
  heatLevels?: number;
  siteId?: number;
  ts?: number;
  /** attester keypair; defaults to the provider wallet */
  attester?: Keypair;
}

/** Signs a §4.3 message with the test server key and sends [ed25519, record_scan]. */
export async function recordScan(
  program: Program<any>,
  provider: anchor.AnchorProvider,
  reg: RegistryHandle,
  p: PassportHandle,
  o: ScanOpts
): Promise<PublicKey> {
  const attester = o.attester?.publicKey ?? provider.wallet.publicKey;
  const args = {
    counter: o.counter,
    tier: o.tier ?? enums.tier.SELF_MEDIA,
    role: o.role ?? enums.role.SELLER,
    tamper: enums.tamper.UNKNOWN,
    uv: enums.indicator.MISSING,
    hum: o.hum ?? enums.indicator.INTACT,
    heat: o.heat ?? enums.indicator.INTACT,
    heatLevels: o.heatLevels ?? 0,
    fill: o.fill,
    siteId: o.siteId ?? 0,
    mediaHash: bytes(randomBytes(32)),
    bundleHash: bytes(randomBytes(32)),
    nonce: bytes(randomBytes(32)),
    ts: new BN(o.ts ?? Math.floor(Date.now() / 1000)),
    serverKeyId: reg.serverKeyId,
  };
  const msg = buildScanMessage({
    serialHash: p.serialHash,
    uidHash: p.uidHash,
    counter: args.counter,
    tamper: args.tamper,
    uv: args.uv,
    hum: args.hum,
    heat: args.heat,
    fill: args.fill,
    mediaHash: Buffer.from(args.mediaHash),
    nonce: Buffer.from(args.nonce),
    ts: BigInt(args.ts.toString()),
  });
  const scanProof = scanPdaOf(program.programId, p.sealPda, o.counter);
  const b = program.methods
    .recordScan(args)
    .accountsStrict({
      registry: reg.registryPda,
      passport: p.passportPda,
      seal: p.sealPda,
      scanProof,
      attester,
      instructions: SYSVAR_INSTRUCTIONS_PUBKEY,
      systemProgram: SystemProgram.programId,
    })
    .preInstructions([ed25519Ix(msg, signMessage(msg))]);
  if (o.attester) b.signers([o.attester]);
  await b.rpc();
  return scanProof;
}

export async function airdrop(provider: anchor.AnchorProvider, to: PublicKey, sol = 2) {
  const sig = await provider.connection.requestAirdrop(to, sol * anchor.web3.LAMPORTS_PER_SOL);
  await provider.connection.confirmTransaction(sig, "confirmed");
}
