#!/usr/bin/env python3
"""
Copy docs/enums.json (generated by packages/proof, the single source of truth)
to apps/verify/fv/enums.json. The server loads enums from the local copy at
import time; tests/test_enums.py asserts both files are identical.

Run from anywhere:  uv run python scripts/sync_enums.py
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP_DIR = HERE.parent                      # apps/verify
REPO_DIR = APP_DIR.parent.parent           # flaconvault/
SRC = REPO_DIR / "docs" / "enums.json"
DST = APP_DIR / "fv" / "enums.json"


def main() -> int:
    if not SRC.exists():
        print(f"source missing: {SRC} (run `npm run vectors` in packages/proof first)", file=sys.stderr)
        return 1
    json.loads(SRC.read_text(encoding="utf-8"))  # must be valid JSON
    shutil.copyfile(SRC, DST)
    print(f"synced {SRC} -> {DST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
